### ISSUE TITLE
problems with version in ppa

### ISSUE THREAD

**Issue by revast** [jrosener/digitalscratch#98]
hi, witnessed some problems with ppa version:

quitting the gui does not quit digitalscratch; have to kill it by hand. (14.04)
the searching music bar  with the "search animation" at bottom does not go away, it is displayed the whole time..
would be nice if this get fixed.. shall I try from git? Btw, are there more Vinyls supported in git version?

**Comment by jrosener** [comment]
Hi,

> quitting the gui does not quit digitalscratch; have to kill it by hand. (14.04)

Indeed it looks like it is because of the "search animation" which is not finished because the analysis of the file browser directory is not done (probably too much files to browse). For the moment this analysis is blocking the UI, this is not good, I should change that (no fix for the moment in git).
So either you wait a bit more to get the file analysis done, or you can change the `base_dir_path` in the config file (`$HOME/.config/digitalscratch.conf`).

> Btw, are there more Vinyls supported in git version?

Nothing more in Git, for the moment there are:
* Serato Scratch Live (CV02)
* Final Scratch (Standard 2.0)
* Mixvibes DVS

Actually I do not have other vinyls, that's why DigitalScratch only support this list. But which vinyl would you like to be supported ? If it is not too different than Serato, FS or Mixvibes, then it is maybe not a big deal to support it.

**Comment by revast** [comment]
well that's it, even if there is nothing there in the default path ~/Music, it does not stop searching. and the stop button also does nothing.

> But which vinyl would you like to be supported ?
was just curious

**Comment by jrosener** [comment]
> On commandline, I get
> QSQLITE driver not loaded
> QSqlDatabase a vailable drivers:

Well, it is indeed something else than what I told you. Maybe the package managing the SQL in Qt is not installed. I will install a fresh 14.04 without any additional packages and check if DigitalScratch is working. For your informations, some data about audio files are stored in a tiny database (SQLite), especially music key and cue points.
Or maybe you installed manually another Qt version than the one packaged with Ubuntu 14.04 ?

**Comment by revast** [comment]
solved. my inspection shows that ds links to libqt5sql5, while I indeed use qt 5.3.2 from ppa, this is not the problem. I discovered that your ds' .debian packages dependencies miss libqt5sql5-sql, if this package is installed, everything is fine ;-)

**Comment by jrosener** [comment]
I am not a debian/ubuntu package expert.
The package `digitalscratch` depends of `qt5-default` (http://packages.ubuntu.com/trusty/qt5-default) which depends of `qtbase5-dev` which depends of `libqt5sql5`. Howover this last package `libqt5sql5` only *recommends* installation of `libqt5sql5-sqlite`. That's why maybe I should add it explicitely as a dependency in the configuration of the package.
But in the mean time I just installed a brand new Ubuntu 14.04.1 without any additionnal installs: I can install and start DigitalScratch with no issue (using the default Qt 5.2.1).

So as a conclusion, I have no idea if it is necessary or not to add the dependency `libqt5sql5-sqlite`...

**Comment by revast** [comment]
right, ok. 
I think it definitely would not harm at all to add this extra dependency, as you definitely use the sqlite driver.

**Comment by jrosener** [comment]
Yes you're right. I will add it for the next PPA. Thank you for the report and discussion!
